version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      time: "09:00"
      timezone: "Asia/Taipei"
  - package-ecosystem: npm
    directories:
      - /
      - /packages/cube-frontend-api
      - /packages/cube-frontend-keycloak-login
      - /packages/cube-frontend-ui-library
      - /packages/cube-frontend-ui-theme
      - /packages/cube-frontend-utils
      - /packages/cube-frontend-web-app
      - /packages/cube-frontend-i18n
    schedule:
      interval: weekly
      day: monday
      time: "09:00"
      timezone: "Asia/Taipei"
    open-pull-requests-limit: 0
    groups:
      minor-and-patch:
        applies-to: version-updates
        update-types: 
          - "minor"
          - "patch"
      sec-minor-and-patch:
        applies-to: security-updates
        update-types: 
          - "minor"
          - "patch"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
