name: Build cube-cos-login RPM

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@05e31511f85b41b11d1cf0ef85d0992719546e2c # v2.21.0
        with:
          egress-policy: audit

      - name: Pulling from Github
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Install pnpm
        uses: pnpm/action-setup@0977fd99725f1db4007ccb2928dbb4e90d06cc86 # v6.0.10

      - name: Use Node.js
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: 24.15.0
          cache: "pnpm"

      - name: Install RPM Build Tool
        run: |
          sudo apt-get update
          sudo apt-get install -y rpm
          rpm --version

      - name: Set ENV
        run: |
          echo "VERSION=$(node -p "require('./packages/cube-frontend-keycloak-login/package.json').version")" >> $GITHUB_ENV
          echo "BUILD_NUMBER=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
          echo "KEYCLOAK_VERSION=$(head -n 1 ./packages/cube-frontend-keycloak-login/KEYCLOAK_VERSION)" >> $GITHUB_ENV

      - name: Create RPM Build Directory
        run: |
          rm -rf ~/rpmbuild
          pushd ~
          mkdir rpmbuild
          cd rpmbuild
          mkdir BUILD RPMS SOURCES SPECS SRPMS
          popd

      - name: Prepare Source Tarball
        run: |
          mkdir ~/source
          cp -r ./.git/ ~/source/
          pushd ~/source
          git checkout .
          sudo rm -r ./.git/
          popd
          pushd ~
          tar -cvzf "cube-cos-login-${VERSION}.tar.gz" source
          mv "cube-cos-login-${VERSION}.tar.gz" ~/rpmbuild/SOURCES
          rm -r source/
          popd

      - name: Copy SPEC File
        run: |
          cp ./packages/cube-frontend-keycloak-login/cube-cos-login.spec ~/rpmbuild/SPECS

      - name: Build RPM
        run: |
          rpmbuild -bb --nodeps --define "version $VERSION" --define "build_number $BUILD_NUMBER" --define "keycloak_version $KEYCLOAK_VERSION" ~/rpmbuild/SPECS/cube-cos-login.spec

      - name: Create a Release
        env:
          GH_TOKEN: ${{ github.token }}
          REF: ${{ github.ref_name }}
        run: |
          BUILD=$(ls ~/rpmbuild/RPMS/x86_64/ | cut -d" " -f1)
          if [[ "$REF" =~ ^v[0-9]+\.[0-9]+\.[0-9]+ ]] ; then \
            TAG="cube-cos-login-$REF"
          else
            TAG="cube-cos-login-$VERSION-dev-$BUILD_NUMBER"
          fi
          gh release create "$TAG" \
            --repo "$GITHUB_REPOSITORY" \
            --target "$GITHUB_SHA" \
            --generate-notes \
            ~/rpmbuild/RPMS/x86_64/$BUILD
