name: Build cube-cos-ui RPM

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@0634a2670c59f64b4a01f0f96f84700a4088b9f0 # v2.12.0
        with:
          egress-policy: audit

      - name: Pulling from Github
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Install pnpm
        uses: pnpm/action-setup@a7487c7e89a18df4991f7f222e4898a00d66ddda # v4.1.0
        with:
          version: 9

      - name: Use Node.js
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: 22
          cache: 'pnpm'

      - name: Install RPM Build Tool
        run: |
          sudo apt-get update
          sudo apt-get install -y rpm
          rpm --version

      - name: Set ENV
        run: |
          echo "VERSION=$(node -p "require('./packages/cube-frontend-web-app/package.json').version")" >> $GITHUB_ENV
          echo "BUILD_NUMBER=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Create RPM Build Directory
        run: |
          rm -rf ~/rpmbuild
          pushd ~
          mkdir rpmbuild
          cd rpmbuild
          mkdir BUILD RPMS SOURCES SPECS SRPMS
          popd

      - name: Prepare Source Tarball
        run: |
          mkdir ~/source
          cp -r ./.git/ ~/source/
          pushd ~/source
          git checkout .
          sudo rm -r ./.git/
          popd
          pushd ~
          tar -cvzf "cube-cos-ui-${VERSION}.tar.gz" source
          mv "cube-cos-ui-${VERSION}.tar.gz" ~/rpmbuild/SOURCES
          rm -r source/
          popd

      - name: Copy SPEC File
        run: |
          cp ./packages/cube-frontend-web-app/cube-cos-ui.spec ~/rpmbuild/SPECS

      - name: Build RPM
        run: |
          rpmbuild -bb --nodeps --define "version $VERSION" --define "build_number $BUILD_NUMBER" ~/rpmbuild/SPECS/cube-cos-ui.spec

      - name: Create a Release
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          BUILD=$(ls ~/rpmbuild/RPMS/x86_64/ | cut -d" " -f1)
          gh release create "cube-cos-ui-$VERSION-dev-$BUILD_NUMBER" \
            --repo "$GITHUB_REPOSITORY" \
            --target "$GITHUB_SHA" \
            --generate-notes \
            ~/rpmbuild/RPMS/x86_64/$BUILD
