name: Build cube-cos-login RPM

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@c6295a65d1254861815972266d5933fd6e532bdf # v2.11.1
        with:
          egress-policy: audit

      - name: Pulling from Github
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Install pnpm
        uses: pnpm/action-setup@a7487c7e89a18df4991f7f222e4898a00d66ddda # v4.1.0
        with:
          version: 9

      - name: Use Node.js
        uses: actions/setup-node@cdca7365b2dadb8aad0a33bc7601856ffabcc48e # v4.3.0
        with:
          node-version: 22
          cache: 'pnpm'

      - name: Install RPM Build Tool
        run: |
          sudo apt-get update
          sudo apt-get install -y rpm
          rpm --version

      - name: Set ENV
        run: |
          echo "VERSION=$(node -p "require('./packages/cube-frontend-keycloak-login/package.json').version")" >> $GITHUB_ENV
          echo "BUILD_NUMBER=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
          echo "KEYCLOAK_VERSION=$(head -n 1 ./packages/cube-frontend-keycloak-login/KEYCLOAK_VERSION)" >> $GITHUB_ENV

      - name: Create RPM Build Directory
        run: |
          rm -rf ~/rpmbuild
          pushd ~
          mkdir rpmbuild
          cd rpmbuild
          mkdir BUILD RPMS SOURCES SPECS SRPMS
          popd

      - name: Prepare Source Tarball
        run: |
          mkdir ~/source
          cp -r ./.git/ ~/source/
          pushd ~/source
          git checkout .
          sudo rm -r ./.git/
          popd
          pushd ~
          tar -cvzf "cube-cos-login-${VERSION}.tar.gz" source
          mv "cube-cos-login-${VERSION}.tar.gz" ~/rpmbuild/SOURCES
          rm -r source/
          popd

      - name: Copy SPEC File
        run: |
          cp ./packages/cube-frontend-keycloak-login/cube-cos-login.spec ~/rpmbuild/SPECS

      - name: Build RPM
        run: |
          rpmbuild -bb --nodeps --define "version $VERSION" --define "build_number $BUILD_NUMBER" --define "keycloak_version $KEYCLOAK_VERSION" ~/rpmbuild/SPECS/cube-cos-login.spec

      - name: Create a Release
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          BUILD=$(ls ~/rpmbuild/RPMS/x86_64/ | cut -d" " -f1)
          gh release create "cube-cos-login-$VERSION-dev-$BUILD_NUMBER" \
            --repo "$GITHUB_REPOSITORY" \
            --target "$GITHUB_SHA" \
            --generate-notes \
            ~/rpmbuild/RPMS/x86_64/$BUILD
