name: Fast Forward Merge

on:
  pull_request_target:
    types:
      - labeled

permissions:
  contents: read

jobs:
  merge:
    permissions:
      contents: write  # for Git to git push
    if: ${{ github.event.label.name == 'done' && github.event.pull_request.mergeable == true }}
    runs-on: ubuntu-latest
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@05e31511f85b41b11d1cf0ef85d0992719546e2c # v2.21.0
        with:
          egress-policy: audit

      - name: Check Out PR Target Branch
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Merge
        env: 
          TOPIC_BRANCH: ${{ github.head_ref }}
        run: |
          git pull origin $TOPIC_BRANCH
          git checkout $TOPIC_BRANCH
          git checkout @{-1}
          git branch
          git merge --ff-only $TOPIC_BRANCH
          git push
